Repository kyutech-programming-club/lt-hub, pull requests merged in 2021-01, with the labels that each got.

#109 eslintとprettierの導入
  .eslintrc.js
  package-lock.json
  package.json
Labels: enhancement

#110 認証機能の修正
  src/components/GoogleAuth.vue
  src/components/Header.vue
  src/types/user.ts
Labels: bug

#111 fix: #104 Delete talkIds in order when user cancel a participation
  src/views/Event.vue
Labels: bug

#112 feat: #106 Change color of participating event-card
  src/components/EventItem.vue
  src/views/Events.vue
Labels: enhancement

#114 refacter: #113 Replace then with async
  src/components/GoogleAuth.vue
Labels: reactor

#115 コメントフォームを改善した
  src/components/CommentBoard.vue
  src/views/Talk.vue
Labels: enhancement

#116 feat #102 Replace updated() scope
  src/components/CommentBoard.vue
Labels: bug

#117 ver1.1.2
  src/components/CommentBoard.vue
  src/components/EventItem.vue
  src/views/Event.vue
  src/views/Events.vue
  src/views/Talk.vue
Labels: enhancement

#122 Refactor/#120 bring type to user of firestore
  package-lock.json
  src/components/GoogleAuth.vue
  src/firebase/firestore.ts
  src/types/user.ts
Labels: reactor

#123 Feat/#121 add vuex
  package-lock.json
  package.json
  src/main.ts
  src/store/index.ts
  src/views/Home.vue
Labels: enhancement
